### ISSUE TITLE
Simulation Crash opening Talon Window

### ISSUE THREAD

**Issue by keplersj** [Open-RIO/ToastAPI#21]
If the Talons are given power before the window is opened, and the user attempts to open the Window after the Simulation GUI crashes.

Full Crash Report:

```
 ________    ______                 __   
((       )  /_  __/___  ____ ______/ /_  
||  o o  |   / / / __ \/ __ `/ ___/ __/  
||   3   |  / / / /_/ / /_/ (__  ) /_    
\\_______/ /_/  \____/\__,_/____/\__/    

[09/02/16-01:47:11] [Toast] [Bootstrap] [INFO] Toast Version: 2.4.4
[09/02/16-01:47:11] [Toast] [Bootstrap] [INFO] Toast Commit Hash: 074932c
[09/02/16-01:47:11] [Toast] [Core-Initialization] [INFO] Toast Started with Run Arguments: [-sim]
[09/02/16-01:47:11] [Toast] [Pre-Initialization] [INFO] Slicing Loaf...
[09/02/16-01:47:14] [Toast] [Initialization] [INFO] Nuking Toast...
platform: /Mac OS X/x86_64/
[09/02/16-01:47:15] [Toast] [Pre-Start] [INFO] Buttering Bread...
[09/02/16-01:47:15] [Toast|Loader] [Pre-Start] [INFO] Module Loaded: Mr. Roboto - Team 5933 - Main Robot Module@0.1.1
[09/02/16-01:47:15] [Toast|Loader] [Pre-Start] [INFO] Module Loaded: Like A Record - Team 5933 - Motor Control@0.1.0
[09/02/16-01:47:15] [Toast|Loader] [Pre-Start] [INFO] Module Loaded: Electric Feel - Team 5933 - Rumble Feedback@0.1.0
[09/02/16-01:47:15] [Toast] [Start] [INFO] Fabricating Sandwich...
[09/02/16-01:47:15] [Toast] [Start] [INFO] Verdict: Hot, Hot, HOT!!
[09/02/16-01:47:15] [Toast] [Main] [INFO] Total Initiation Time: 4.378 seconds
Robot Drive... Output not updated often enough.
**** CRASH LOG ****
Your robot has crashed. Following is a crash log and more details.
This log has been saved to: /Users/kepler/Developer/Judgement Call/Mr. Roboto/run/gradle/simulation/toast/crash/crash-2016-02-09_01-48-38.txt
This log will also be duplicated to USB devices, with the filename: crash-2016-02-09_01-48-38.txt
 ________     __  ____       ____  __
((       )   / / / / /_     / __ \/ /_
||  x x  |  / / / / __ \   / / / / __ \
||   ^   | / /_/ / / / /  / /_/ / / / /
\\_______/ \____/_/ /_/   \____/_/ /_/

java.lang.NullPointerException
    at jaci.openrio.toast.core.loader.simulation.srx.GuiSRX.update(GuiSRX.java:46)
    at jaci.openrio.toast.core.loader.simulation.srx.GuiSRX$$Lambda$27/1388693377.run(Unknown Source)
    at jaci.openrio.toast.core.loader.simulation.srx.SRX_Reg$SRX_Wrapper.update(SRX_Reg.java:36)
    at jaci.openrio.toast.core.loader.simulation.srx.SRX_Reg$SRX_Wrapper.setVBus(SRX_Reg.java:57)
    at edu.wpi.first.wpilibj.hal.CanTalonJNI.Set(CanTalonJNI.java:143)
    at edu.wpi.first.wpilibj.CANTalon.set(CANTalon.java:430)
    at edu.wpi.first.wpilibj.CANTalon.set(CANTalon.java:491)
    at edu.wpi.first.wpilibj.RobotDrive.setLeftRightMotorOutputs(RobotDrive.java:632)
    at edu.wpi.first.wpilibj.RobotDrive.arcadeDrive(RobotDrive.java:480)
    at edu.wpi.first.wpilibj.RobotDrive.arcadeDrive(RobotDrive.java:369)
    at edu.wpi.first.wpilibj.RobotDrive.arcadeDrive(RobotDrive.java:383)
    at frc.team5933.motors.Drive.arcadeDrive(Drive.java:48)
    at frc.team5933.motors.MotorControl.teleopPeriodic(MotorControl.java:58)
    at jaci.openrio.toast.lib.module.IterativeModule.tickState(IterativeModule.java:30)
    at jaci.openrio.toast.core.StateTracker.tick(StateTracker.java:130)
    at jaci.openrio.toast.core.StateTracker.init(StateTracker.java:102)
    at jaci.openrio.toast.core.Toast.startCompetition_2(Toast.java:123)
    at jaci.openrio.toast.core.Toast.startCompetition(Toast.java:88)
    at jaci.openrio.toast.core.ToastBootstrap.fakeRobotBase(ToastBootstrap.java:247)
    at jaci.openrio.toast.core.ToastBootstrap.main(ToastBootstrap.java:210)

Crash Information: 
    Toast: 
        Toast Version: 2.4.4
        Loaded Modules:
            Mr. Roboto - Team 5933 - Main Robot Module@0.1.1
            Like A Record - Team 5933 - Motor Control@0.1.0
            Electric Feel - Team 5933 - Rumble Feedback@0.1.0

    Environment: 
            Toast: 2.4.4
              Git: 074932c (074932cf75491f81829aa387c16ff92268797f83)
             Type: Simulation
              FMS: false
               OS: Mac OS X 10.11.1 (x86_64)
             Java: 1.8.0_45 (Oracle Corporation)
        Java Path: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
          JScript: Supported (Nashorn)

    Modules: 
        Mr. Roboto - Team 5933 - Main Robot Module
            Name: Mr. Roboto - Team 5933 - Main Robot Module
            Version: 0.1.1
            File: /Users/kepler/Developer/Judgement Call/Mr. Roboto/run/gradle/simulation/toast/modules/Mr. Roboto - Main Robot Module.jar
            Bypass Class: null
            Core Module Class: null
            Owned Packages: 
                frc.team5933
                com
                edu.wpi.first.wpilibj
                jaci.openrio
        Like A Record - Team 5933 - Motor Control
            Name: Like A Record - Team 5933 - Motor Control
            Version: 0.1.0
            File: /Users/kepler/Developer/Judgement Call/Mr. Roboto/run/gradle/simulation/toast/modules/Mr. Roboto - Main Robot Module.jar
            Bypass Class: null
            Core Module Class: null
            Owned Packages: 
                frc.team5933
                com
                edu.wpi.first.wpilibj
                jaci.openrio
        Electric Feel - Team 5933 - Rumble Feedback
            Name: Electric Feel - Team 5933 - Rumble Feedback
            Version: 0.1.0
            File: /Users/kepler/Developer/Judgement Call/Mr. Roboto/run/gradle/simulation/toast/modules/Mr. Roboto - Main Robot Module.jar
            Bypass Class: null
            Core Module Class: null
            Owned Packages: 
                frc.team5933
                com
                edu.wpi.first.wpilibj
                jaci.openrio


*******************
```

[Repo with Crashing Code](https://github.com/jmchs-robotics/2016-mr_roboto)

**Comment by JaciBrunning** [comment]
I'll take a look into this.

(by the way, nice module names :+1:)

**Comment by keplersj** [comment]
Thank you!
