### ISSUE TITLE
ADXL362 doesn't work in simulation

### ISSUE THREAD

**Issue by ariovistus** [Open-RIO/ToastAPI#34]
```
**** CRASH LOG ****
Your robot has crashed. Following is a crash log and more details.
This log has been saved to: /home/ellery/repos/robot2016/robot2016/run/gradle/simulation/toast/crash/crash-2016-02-29_04-58-37.txt
This log will also be duplicated to USB devices, with the filename: crash-2016-02-29_04-58-37.txt
 ________     __  ____       ____  __
((       )   / / / / /_     / __ \/ /_
||  x x  |  / / / / __ \   / / / / __ \
||   ^   | / /_/ / / / /  / /_/ / / / /
\\_______/ \____/_/ /_/   \____/_/ /_/

java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at jaci.openrio.toast.core.loader.MethodExecutor.call(MethodExecutor.java:106)
    at jaci.openrio.toast.core.loader.MethodExecutor.call(MethodExecutor.java:42)
    at jaci.openrio.toast.core.loader.RobotLoader.dispatch(RobotLoader.java:462)
    at jaci.openrio.toast.core.loader.RobotLoader.start(RobotLoader.java:445)
    at jaci.openrio.toast.core.Toast.startCompetition_2(Toast.java:108)
    at jaci.openrio.toast.core.Toast.startCompetition(Toast.java:88)
    at jaci.openrio.toast.core.ToastBootstrap.fakeRobotBase(ToastBootstrap.java:275)
    at jaci.openrio.toast.core.ToastBootstrap.main(ToastBootstrap.java:238)
Caused by: java.lang.UnsatisfiedLinkError: edu.wpi.first.wpilibj.hal.SPIJNI.spiInitialize(B)V
    at edu.wpi.first.wpilibj.hal.SPIJNI.spiInitialize(Native Method)
    at edu.wpi.first.wpilibj.SPI.<init>(SPI.java:57)
    at edu.wpi.first.wpilibj.ADXL362.<init>(ADXL362.java:85)
    at frc.team3223.robot2016.SensorManager.<init>(SensorManager.java:25)
    at frc.team3223.robot2016.RobotConfiguration.<init>(RobotConfiguration.java:61)
    at frc.team3223.robot2016.RobotModule.robotInit(RobotModule.java:69)
    at jaci.openrio.toast.lib.module.IterativeModule.start(IterativeModule.java:75)
    ... 12 more

Crash Information: 
    Toast: 
        Toast Version: 2.4.8
        Loaded Modules:
            robot2016@0.0.1

    Environment: 
            Toast: 2.4.8
              Git: 0562471 (056247184a2120245c09767bcfc2cf38a62e81aa)
             Type: Simulation
              FMS: false
               OS: Linux 4.3.5-300.fc23.x86_64 (amd64)
             Java: 1.8.0_72 (Oracle Corporation)
        Java Path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.72-4.b15.fc23.x86_64/jre
          JScript: Supported (Nashorn)

    Modules: 
        robot2016
            Name: robot2016
            Version: 0.0.1
            File: /home/ellery/repos/robot2016/robot2016/run/gradle/simulation/toast/modules/robot2016.jar
            Bypass Class: null
            Core Module Class: null
            Owned Packages: 
                frc.team3223
```

**Comment by JaciBrunning** [comment]
Unfortunately SPI isn't supported in simulation, due to the fact that the SPI JNI (the things that communicates with the SPI bus), doesn't actually tell us what it's communicating to. As different SPI devices (Gyro, Arduino, what have you), use different formats for sending data over the bus, it's impossible for us to derive exactly what device to simulate. 

I would recommend changing your code to use a `if (Environment.isSimulation()) {}` block before creating the object. You can insert your own code to act as a substitute while simulating.
