### ISSUE TITLE
Simulation crashes with all sensors

### ISSUE THREAD

**Issue by emilyastranova** [Open-RIO/ToastAPI#37]
---

((       )  /_  **/_**  ____ ______/ /_  
||  o o  |   / / / __ \/ __ `/ **_/ __/  
||   3   |  / / / /_/ / /_/ (**  ) /_  
\_______/ /_/  ____/__,_/____/__/    

[11/03/16-09:46:44] [Toast] [Bootstrap] [INFO] Toast Version: 2.4.9
[11/03/16-09:46:44] [Toast] [Bootstrap] [INFO] Toast Commit Hash: 0c7de66
[11/03/16-09:46:44] [Toast] [Core-Initialization] [INFO] Toast Started with Run Arguments: [-sim]
[11/03/16-09:46:44] [Toast] [Pre-Initialization] [INFO] Slicing Loaf...
[11/03/16-09:46:46] [Toast] [Initialization] [INFO] Nuking Toast...
platform: /Windows/amd64/
[11/03/16-09:46:46] [Toast] [Thread-7] [INFO] Toast Driver Station Networking Bonjour Tunnel successfully configured!
[11/03/16-09:46:46] [Toast] [Pre-Start] [INFO] Buttering Bread...
[11/03/16-09:46:46] [Toast|Loader] [Pre-Start] [INFO] Module Loaded: FRCUserProgram.jar!wrapper@0.0.0
[11/03/16-09:46:46] [Toast] [Start] [INFO] Fabricating Sandwich...
[11/03/16-09:46:46] [Toast] [Start] [INFO] Verdict: Yummy
[11/03/16-09:46:46] [Toast] [Main] [INFO] Total Initiation Time: 1.911 seconds
[11/03/16-09:46:46] [Toast] [Thread-9] [ERROR] Could not instantiate Wrapped Module reflection on robotInit: java.lang.reflect.InvocationTargetException
[11/03/16-09:46:46] [Toast] [Thread-9] [ERROR] java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at jaci.openrio.toast.lib.module.ModuleWrapper.reflectMethod(ModuleWrapper.java:150)
    at jaci.openrio.toast.lib.module.ModuleWrapper.lambda$start$8(ModuleWrapper.java:92)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: edu.wpi.first.wpilibj.hal.EncoderJNI.initializeEncoder(BIZBIZZLjava/nio/IntBuffer;)J
    at edu.wpi.first.wpilibj.hal.EncoderJNI.initializeEncoder(Native Method)
    at edu.wpi.first.wpilibj.Encoder.initEncoder(Encoder.java:87)
    at edu.wpi.first.wpilibj.Encoder.<init>(Encoder.java:129)
    at edu.wpi.first.wpilibj.Encoder.<init>(Encoder.java:141)
    at org.usfirst.frc4328.Robot2016.RobotMap.init(RobotMap.java:82)
    at org.usfirst.frc4328.Robot2016.Robot.robotInit(Robot.java:65)
    ... 7 more

***\* CRASH LOG ****
Your robot has crashed. Following is a crash log and more details.
This log has been saved to: C:\Users\FuriousFalcons\Desktop\ToastAPI-master\release\run\gradle\simulation\toast\crash\crash-2016-03-11_09-47-26.txt
This log will also be duplicated to USB devices, with the filename: crash-2016-03-11_09-47-26.txt

---

((       )   / / / / /_     / __ \/ /_
||  x x  |  / / / / __ \   / / / / __ \
||   ^   | / /_/ / / / /  / /_/ / / / /
\_______/ _**_/_/ /_/   __**/_/ /_/

java.lang.NullPointerException
    at org.usfirst.frc4328.Robot2016.Robot.teleopPeriodic(Robot.java:135)
    at jaci.openrio.toast.lib.module.ModuleWrapper.lambda$stateSetup$9(ModuleWrapper.java:119)
    at jaci.openrio.toast.core.StateTracker.tick(StateTracker.java:130)
    at jaci.openrio.toast.core.StateTracker.init(StateTracker.java:102)
    at jaci.openrio.toast.core.Toast.startCompetition_2(Toast.java:123)
    at jaci.openrio.toast.core.Toast.startCompetition(Toast.java:88)
    at jaci.openrio.toast.core.ToastBootstrap.fakeRobotBase(ToastBootstrap.java:275)
    at jaci.openrio.toast.core.ToastBootstrap.main(ToastBootstrap.java:238)

Crash Information: 
    Toast: 
        Toast Version: 2.4.9
        Loaded Modules:
            FRCUserProgram.jar!wrapper@0.0.0

```
Environment: 
        Toast: 2.4.9
          Git: 0c7de66 (0c7de66be66f1b5e42343f83bc9188a359969abc)
         Type: Simulation
          FMS: false
           OS: Windows 10 10.0 (amd64)
         Java: 1.8.0_66 (Oracle Corporation)
    Java Path: C:\Program Files\Java\jdk1.8.0_66\jre
      JScript: Supported (Nashorn)

Modules: 
    FRCUserProgram.jar!wrapper
        Name: FRCUserProgram.jar!wrapper
        Version: 0.0.0
        File: C:\Users\FuriousFalcons\Desktop\ToastAPI-master\release\run\gradle\simulation\toast\modules\FRCUserProgram.jar
        Bypass Class: null
        Core Module Class: null
        Owned Packages: 
            org.usfirst.frc4328.Robot2016
            edu.wpi.first.wpilibj
            com.ni.vision
        Custom Data: 
            Sample: false
            Iterative: true
            Wrapped Class: org.usfirst.frc4328.Robot2016.Robot
```

---

Does this when I take encoders out (ultrasonic sensors). I only need to test the encoders and ultrasonic so if these cause crashes I have a severe problem...

**Comment by emilyastranova** [comment]
I should add that when I take the encoders out it's the ultrasonic that cause errors. I did not put the encoders in as ultrasonics.

**Comment by JaciBrunning** [comment]
Encoders and Analog / SPI Sensors are not supported in simulation. For specific sensors, you will have to write your own simulation code for. There is no possible way for Toast to simulate things like ultrasonic sensors
